const fs=require('fs'), path=require('path');
const ROOT=__dirname, BASE='https://www.hrw.org';
fs.mkdirSync(path.join(ROOT,'data'),{recursive:true});
const clean=s=>s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const attr=(s,n)=>{const m=s.match(new RegExp('\\b'+n+'=["\']([^"\']*)["\']','i'));return m?m[1]:''};
const queue=[BASE+'/',BASE+'/sitemap'], seen=new Set(queue), found=new Map(), pages=[], skipped=new Set();
let rules=[],active=0, requests=0;
function allowed(u){const p=new URL(u);if(p.hostname!=='www.hrw.org')return false;const v=p.pathname+p.search;return !rules.some(r=>new RegExp('^'+r.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*')).test(v)) && !/\.(pdf|docx?|jpg|jpeg|png|gif|svg|mp4|zip|xml)$/i.test(p.pathname);}
function normalize(h,u){try{const v=new URL(h.replace(/&amp;/g,'&'),u);v.hash='';if(v.hostname==='hrw.org')v.hostname='www.hrw.org';if(!['http:','https:'].includes(v.protocol))return null;v.protocol='https:';return v.href.replace(/\/$/,'')===BASE?BASE+'/':v.href;}catch{return null}}
async function get(u){const r=await fetch(u,{headers:{'User-Agent':'InspirationResearch/1.0 (public website design review)'},signal:AbortSignal.timeout(25000)});return {status:r.status,url:r.url,type:r.headers.get('content-type'),html:await r.text()};}
function save(){fs.writeFileSync(path.join(ROOT,'data','pages.json'),JSON.stringify(pages,null,2));fs.writeFileSync(path.join(ROOT,'data','urls.json'),JSON.stringify([...found.values()],null,2));fs.writeFileSync(path.join(ROOT,'data','coverage.json'),JSON.stringify({date:'2026-10-04',requests,reviewed:pages.length,successful:pages.filter(p=>p.status===200).length,discovered:found.size,pending:queue.length,excluded:skipped.size,scope:'Public www.hrw.org HTML, navigation-first discovery. Article bodies not copied. Crawl limited to 500 requests; not an exhaustive archive.',robotsRules:rules},null,2));const q=s=>'"'+String(s??'').replace(/"/g,'""')+'"';fs.writeFileSync(path.join(ROOT,'data','url-inventory.csv'),['url,label,source,status',...[...found.values()].map(x=>[x.url,x.label,x.source,pages.find(p=>p.url===x.url)?.status||'discovered'].map(q).join(','))].join('\n'));}
async function main(){const robots=await get(BASE+'/robots.txt');fs.writeFileSync(path.join(ROOT,'data','robots.txt'),robots.html);let general=false;for(const line of robots.html.split('\n')){if(/^User-agent:/i.test(line))general=line.trim()==='User-agent: *';else if(general&&/^Disallow:/i.test(line)){const p=line.slice(9).trim();if(p)rules.push(p)}}
async function worker(){while(queue.length&&requests<500){const u=queue.shift();requests++;active++;try{const r=await get(u);const h=r.html;const headings=[...h.matchAll(/<(h[1-6])\b[^>]*>([\s\S]*?)<\/\1>/gi)].map(m=>({level:m[1],text:clean(m[2])}));const links=[...h.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map(m=>({url:normalize(attr(m[1],'href'),r.url),label:clean(m[2]).slice(0,180)})).filter(x=>x.url);for(const l of links){if(!found.has(l.url))found.set(l.url,{...l,source:u});if(allowed(l.url)&&!seen.has(l.url)&&!new URL(l.url).search){seen.add(l.url);queue.push(l.url)}else if(!allowed(l.url))skipped.add(l.url)}
const meta=[...h.matchAll(/<meta\b([^>]*)>/gi)].map(m=>({name:attr(m[1],'name')||attr(m[1],'property'),content:attr(m[1],'content')})).filter(x=>x.name);
pages.push({url:u,finalURL:r.url,status:r.status,title:clean(h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),language:attr(h.match(/<html[^>]*>/i)?.[0]||'','lang'),direction:attr(h.match(/<html[^>]*>/i)?.[0]||'','dir'),headings,meta,stylesheets:[...h.matchAll(/<link\b[^>]*>/gi)].filter(m=>attr(m[0],'rel')==='stylesheet').map(m=>normalize(attr(m[0],'href'),r.url)),forms:[...h.matchAll(/<(input|select|button|textarea)\b([^>]*)>/gi)].map(m=>({tag:m[1],type:attr(m[2],'type'),name:attr(m[2],'name'),placeholder:attr(m[2],'placeholder'),'aria-label':attr(m[2],'aria-label')})),images:[...h.matchAll(/<img\b[^>]*>/gi)].map(m=>({src:normalize(attr(m[0],'src'),r.url),alt:attr(m[0],'alt'),width:attr(m[0],'width'),height:attr(m[0],'height')})),links:links.length,bytes:Buffer.byteLength(h)});
}catch(e){pages.push({url:u,status:'error',error:e.message})}active--;if(pages.length%25===0){save();console.log(JSON.stringify({reviewed:pages.length,discovered:found.size,pending:queue.length}))}await new Promise(r=>setTimeout(r,600));}}
await Promise.all([worker(),worker()]);save();console.log('DONE '+JSON.stringify({reviewed:pages.length,discovered:found.size,pending:queue.length}));}
main().catch(e=>{save();console.error(e);process.exitCode=1});
